source ~/.local/share/omacase/defaults/zsh/rc

# Editor used by CLI
export EDITOR="nvim"
export SUDO_EDITOR="$EDITOR"

[ -f /opt/dev/dev.sh ] && source /opt/dev/dev.sh

[[ -x /opt/homebrew/bin/brew ]] && eval $(/opt/homebrew/bin/brew shellenv)